// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM4pVdqrOPOUSxiQufjbLY_SEcnQcD_KU',
    appId: '1:1052414099391:web:ad467ade89bd49fa9d2b0a',
    messagingSenderId: '1052414099391',
    projectId: 'myfirstproject-f32d2',
    authDomain: 'myfirstproject-f32d2.firebaseapp.com',
    storageBucket: 'myfirstproject-f32d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCRigJcBZs0GxjlkwhFqxhiBuDGHRvDsE',
    appId: '1:1052414099391:android:39ed514ab2b6ddd79d2b0a',
    messagingSenderId: '1052414099391',
    projectId: 'myfirstproject-f32d2',
    storageBucket: 'myfirstproject-f32d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq0MDr2fD28nQ-3lBvZW56k7R8PVOC2Hw',
    appId: '1:1052414099391:ios:347599f7c196aa869d2b0a',
    messagingSenderId: '1052414099391',
    projectId: 'myfirstproject-f32d2',
    storageBucket: 'myfirstproject-f32d2.appspot.com',
    iosClientId: '1052414099391-6bu32khitrbfe1s52g6bl89h17v8ejtm.apps.googleusercontent.com',
    iosBundleId: 'com.kintlearn.myfirstproject',
  );
}
